name: Lampac
version: "1.1.10"
slug: lampac
description: Lampac Next Generation
url: https://github.com/lampac-nextgen/lampac

arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false

ports:
  9118/tcp: 9118

ports_description:
  9118/tcp: Lampac HTTP API

map:
  - type: addon_config
    read_only: false
    path: /config

options:
  init_conf: |
    {
      "BaseModule": {
        "LoadModules": [".*"],
        "SkipModules": [
          "Catalog",
          "Tracks",
          "Transcoding",
          "WebLog",
          "CacheMedia",
          "ForkPlayerXML",
          "MsxNative",
          "Potok",
          "TelegramAuth",
          "TelegramAuthBot"
        ]
      },
      "TorrServer": {
        "releases": "latest"
      }
    }

schema:
  init_conf: str

webui: "http://[HOST]:[PORT:9118]/"
