name: Lampac
version: "1.0.0"
slug: lampac
description: Lampac Next Generation

arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false

ports:
  9118/tcp: 9118

ports_description:
  9118/tcp: Lampac HTTP API

map:
  - type: addon_config
    read_only: false
    path: /lampac

webui: "http://[HOST]:[PORT:9118]/"