name: Lampac
version: "1.1.10"
slug: lampac
description: Lampac Next Generation
url: https://github.com/lampac-nextgen/lampac

arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false

ports:
  9118/tcp: 9118

ports_description:
  9118/tcp: Lampac HTTP API

map:
  - type: addon_config
    read_only: false
    path: /config

options:
  init_conf: |
init_conf: |
  {
   "BaseModule": {
     "LoadModules": [".*"],
     "SkipModules": [
       "Catalog",
       "Tracks",
       "Transcoding",
       "WebLog",
       "CacheMedia",
       "ForkPlayerXML",
       "MsxNative",
       "Potok",
       "TelegramAuth",
       "TelegramAuthBot",
       "DLNA",
       "MoonAnime",
       "AnimeLib",
       "AniMedia",
       "AnimeON",
       "Animebesst",
       "AnimeGo",
       "Animevost",
       "AutoEmbed",
       "HydraFlix",
       "MovPI",
       "PlayEmbed",
       "RgShows",
       "SmashyStream",
       "TwoEmbed",
       "VidLink",
       "VidSrc",
       "Videasy",
       "AsiaGe",
       "Geosaitebi",
       "Rezka",
       "Alloha",
       "Filmix",
       "GetsTV",
       "IptvOnline",
       "KinoPub",
       "SakhTV",
       "VoKino",
       "iRemux",
       "Ashdi",
       "BamBoo",
       "Eneyida",
       "HdvbUA",
       "KinoUkr",
       "Tortuga",
       "UAFilm",
       "UaKino",
       "Kinoflix",
       "AniLiberty",
       "Dreamerscast",
       "AniLibria",
       "Kodik",
       "AiLiberty",
       "Mikai",
       "PidTor",
       "CubProxy",
       "TmdbProxy",
     ]
   },
   "TorrServer": {
     "releases": "latest"
   },
   "listen": {
     "localhost": "127.0.0.1"
   },
   "LampaWeb": {
     "customPlugins": [
       {
         "url": "{localhost}/sync/js/home",
         "status": 1
       }
     ],
     "initPlugins": {
       "sync": false,
       "bookmark": false,
       "timecode": false,
       "CubProxy": false,
       "TmdbProxy": false

     }
   }
  }

schema:
  init_conf: str

webui: "http://[HOST]:[PORT:9118]/"
